### ISSUE TITLE
Unity ResolutionFailedException

### ISSUE THREAD

**Issue by topnguyen** [devtrends/Unity.WebAPI#10]
I use your code and when WebApi resolve it throw exception
Microsoft.Practices.Unity.ResolutionFailedException' occurred in Microsoft.Practices.Unity.dll
Type resolve make exception is System.Web.Http.Hosting.IHostBufferPolicySelector
Are you fixed this or already update lastest version?

**Comment by devtrends** [comment]
Closing old issues. This is not a library issue. Unity will throw an exception if the component cannot be resolved. The full exception should help diagnose issue but this is related to Unity, not Unity.WebApi.

**Comment by zgm888** [comment]
Unity.ResolutionFailedException
  HResult=0x80131500
  Message=Resolution failed with error: No public constructor is available for type Intelex.Business.Api.Providers.IApiEdmProvider.
