### ISSUE TITLE
why no need to catch the IHttpController resolve exception?

### ISSUE THREAD

**Issue by billzhuang** [devtrends/Unity.WebAPI#12]
in UnityDependencyScope.cs line 22,
if 

```
if (typeof(IHttpController).IsAssignableFrom(serviceType))
{
        return Container.Resolve(serviceType); // throw exception, how to handle?
 }
```

**Comment by devtrends** [comment]
The [IDependencyResolver help page](https://msdn.microsoft.com/en-us/library/system.web.mvc.idependencyresolver.getservice(v=vs.118).aspx) states that:

> Implementers should return null when the service cannot be found.

This was implemented for all cases except controller resolution where allowing Unity to throw an exception seemed more logical. If the controller cannot be instantiated then your application cannot continue so the exception makes sense here.
