### ISSUE TITLE
Upgrading Unity.Abstractions to 4.0 causes reference issue with Dependency Resolver

### ISSUE THREAD

**Issue by ddivita** [devtrends/Unity.WebAPI#16]
Error	CS0012	The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'.

**Comment by serhioV** [comment]
any solution?

**Comment by Fr4nc3** [comment]
I am having the same issue
Error	CS0012	The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f

Using Unity v5.10.3 and UnityAbstractions v4.1.3

**Comment by mikemikulecky** [comment]
I got around this by building the source myself after updating all the Nuget packages to the latest and boosting the .NET framework version to 4.8--matching my solution.

**Comment by pgossmann** [comment]
I had the same issue and it turned out I used another nuget package **Unity.WebAPI** which in version 5.3.0 seems to reference Unity.Abstractions 2.0.0.0 
I removed that NuGet package and implemented the Dependency Resolver myself using the IUnityContainer of the UnityAbstractions v4.1.3.
Maybe this helps someone.

**Comment by Kartik2016** [comment]
Hi @pgossmann I am facing the same issue and have been stuck for a long time. Can you please share the dependancy resolver code that you implemented so that i can also use your solution. Thank you.

**Comment by mikemikulecky** [comment]
> I got around this by building the source myself after updating all the Nuget packages to the latest and boosting the .NET framework version to 4.8--matching my solution.

It was the Unity.WebAPI package that I rebuilt to fix this, not Abstractions.

**Comment by Kartik2016** [comment]
@mikemikulecky, the app you were working on, is it a Asp .net framework MVC app or simple asp .net framework app?

**Comment by mikemikulecky** [comment]
@Kartik2016 it was an asp.net framework Web API app.

**Comment by Kartik2016** [comment]
@mikemikulecky How can I build from the source my self. If there is any reference link you could provide? Thanks

**Comment by pgossmann** [comment]
The sources are on Github: https://github.com/devtrends/Unity.WebAPI
If you download, you'll see that there are not many classes. 
For myself it was just easier to pick the source of the dependency resolver, adapted it to my needs and included it in my project. 
And yes its a .net Framework 4.7.2 project that was upgraded over the years, thats why I had this dependency in the first place.

**Comment by devtrends** [comment]
Fixed and uploaded a new version to NuGet
