### ISSUE TITLE
Integration with Unity 

### ISSUE THREAD

**Issue by ENikS** [devtrends/Unity.WebAPI#17]
@devtrends 

Would you be interested to merge your libraries with official [Unity Container](https://github.com/unitycontainer) organization and take ownership of webapi and mvs projects?
I have very limited knowledge of both technologies and would really appreciate help with both.

**Comment by ENikS** [comment]
I guess not

**Comment by devtrends** [comment]
Sorry I missed this. I am not opposed to a merge but I am ridiculously busy right now so would not have the time to take ownership. My projects are very little code and are not going to be updated to .NET Core so they currently require minimal work on my part - generally only when Unity introduces a breaking change ;-)
