### ISSUE TITLE
Integrate with Unity organization?

### ISSUE THREAD

**Issue by ENikS** [devtrends/Unity.WebAPI#18]
Paul,

Would you be interested in integrating your project into the [organization](https://github.com/unitycontainer) and take charge of Web API part of it? 

I think your implementation is far more superior to original lib that Unity team implemented. Why not make it official?

**Comment by devtrends** [comment]
Thanks. I have no problem with the project being integrated into the organisation (and see that my Unity.Wcf has already been integrated) but I am really stretched with client projects now so I have virtually no time for any support and would not be able to take charge of anything :-( If you can find someone else to support it and/or you want to integrate the project anyway, let me know and I'll transfer the NuGet ownership.
