### ISSUE TITLE
Resolve returns null on every exception

### ISSUE THREAD

**Issue by szelpe** [devtrends/Unity.WebAPI#5]
```
catch
            {
                return null;
            }            
```

This part caused me trouble, because unity threw a valid Exception which was swallowed by the Resolver.

**Comment by devtrends** [comment]
Sorry for the slightly late reply ;) Yes, I can't remember why I wrote it that way. If you are using the library to resolve controllers with dependencies (which the the major usage pattern) then it will raise an exception if there are any problems. If you are using the DependencyResolver as a service locator then you will need to check for nulls in the case of missing registrations.

**Comment by devtrends** [comment]
Found the reason:
