### ISSUE TITLE
Broken with latest major release of Unity

### ISSUE THREAD

**Issue by tiesmaster** [devtrends/Unity.WebAPI#8]
Similar to [this](https://github.com/roblevine/UnityLog4NetExtension) Unity extension ([issue #5](https://github.com/roblevine/UnityLog4NetExtension/issues/5)): with the new major release of [Unity](https://github.com/unitycontainer/unity), this extension is broken.

Please release a new NuGet package of this.

**Comment by devtrends** [comment]
Closing old issues. Last release resolved this.
